gantt
    title Optional Proofs Security Roadmap (🌾👨🧂)
    dateFormat YYYY-MM-DD
    axisFormat ♦ 

    section Phase 1
    Write down threat model               :p1a, 2026-02-11, 6w
    Agree on launch gating requirements   :p1b, 2026-02-11, 6w
    Reaffirm cryptography requirements    :p1e, 2026-02-11, 6w
    Reaffirm capex targets                :p1f, 2026-02-11, 6w
    Decide on fallback strategy           :p1c, 2026-02-11, 2026-06-01
    Develop MVP testing baseline          :p1g, 2026-02-11, 2026-06-01
    Soundcalc integration                 :p2i, 2026-02-11, 2026-03-01
    100 bits, ≤600KiB proofs, recursion sketch  :p2j, after p2i, 2026-06-01
    Write down diversity requirements     :p1d, after p1b, 2026-06-01
    Develop inclusion criteria            :p1h, after p1b, 2026-06-01
    Validate hardware requirements        :p2g, after p1f, 2026-06-01
    Set inclusion criteria and launch blockers :milestone, 2026-06-01, 0d

    section Phase 2
    Build prover network monitoring       :p2f, 2026-06-01, 2026-11-01
    Implement testing                     :p2b, 2026-06-01, 2026-11-01
    Implement test monitoring             :p2c, 2026-06-01, 2026-11-01
    Reproduce provers                     :p2a, 2026-06-01, 2026-11-01
    128 bits, ≤300KiB proofs, recursion argument :p2j, 2026-06-01, 2026-11-01
    Choose ZKEVMs, set k-tuples           :milestone, 2026-11-01, 0d

    section Phase 3
    Write incident response plans         :p2e, 2026-11-01, 2026-12-01
    Monitor for stability (3 months)      :p3a, 2026-11-01, 2027-02-01
    Test incident response                :p3b, 2026-12-01, 2027-02-01
    Hegotá target                         :milestone, 2027-02-01, 0d

%%
%% flowchart BT
%%     optional_proofs[🚢 optional proofs 🚢]
%%
%%     incident_response_plans[incident response plans]
%%     incident_response_testing[incident response testing]
%%     fallback_plans[fallback plans]
%%     threat_model[threat model]
%%
%%     test_monitoring[test monitoring]
%%     mvp_testing[MVP testing]
%%
%%     mvp_stability[MVP network stability]
%%     prover_network_monitoring[prover network monitoring]
%%     stan_monitoring[stateless attester network monitoring]
%%     hardware_spec[hardware specs]
%%     cluster_reproduction[cluster reproduction]
%%     zkevm_selection[ZKEVM selection]
%%     zkevm_inclusion_criteria[ZKEVM inclusion criteria]
%%     zkevm_diversity_criteria[ZKEVM diversity criteria]
%%     zkevm_security_criteria[ZKEVM security criteria]
%%
%%     mvp_stability --> optional_proofs
%%     cluster_reproduction --> mvp_stability
%%     prover_network_monitoring --> mvp_stability
%%     stan_monitoring --> mvp_stability
%%     zkevm_selection --> cluster_reproduction
%%     zkevm_inclusion_criteria --> zkevm_selection
%%     hardware_spec --> zkevm_inclusion_criteria
%%     zkevm_diversity_criteria --> zkevm_inclusion_criteria
%%     zkevm_security_criteria --> zkevm_inclusion_criteria
%%     threat_model --> prover_network_monitoring
%%     threat_model --> stan_monitoring
%%     threat_model --> zkevm_diversity_criteria
%%
%%     incident_response_plans --> incident_response_testing
%%     incident_response_testing --> optional_proofs
%%     fallback_plans --> incident_response_plans
%%     threat_model --> incident_response_plans
%%
%%     test_monitoring --> optional_proofs
%%     mvp_testing --> test_monitoring
%%
%
%% flowchart BT
%%     optional_proofs[🚢 optional proofs 🚢]
%%
%%     incident_response_plans[incident response plans]
%%     incident_response_testing[incident response testing]
%%     fallback_plans[fallback plans]
%%     threat_model[threat model]
%%
%%     test_monitoring[test monitoring]
%%     mvp_testing[MVP testing]
%%
%%     mvp_stability[MVP network stability]
%%     prover_network_monitoring[prover network monitoring]
%%     stan_monitoring[stateless attester network monitoring]
%%     hardware_spec[hardware specs]
%%     cluster_reproduction[cluster reproduction]
%%     zkevm_selection[ZKEVM selection]
%%     zkevm_inclusion_criteria[ZKEVM inclusion criteria]
%%     zkevm_diversity_criteria[ZKEVM diversity criteria]
%%     zkevm_security_criteria[ZKEVM security criteria]
%%
%%     mvp_stability --> optional_proofs
%%     cluster_reproduction --> mvp_stability
%%     prover_network_monitoring --> mvp_stability
%%     stan_monitoring --> mvp_stability
%%     zkevm_selection --> cluster_reproduction
%%     zkevm_inclusion_criteria --> zkevm_selection
%%     hardware_spec --> zkevm_inclusion_criteria
%%     zkevm_diversity_criteria --> zkevm_inclusion_criteria
%%     zkevm_security_criteria --> zkevm_inclusion_criteria
%%     threat_model --> prover_network_monitoring
%%     threat_model --> stan_monitoring
%%     threat_model --> zkevm_diversity_criteria
%%
%%     incident_response_plans --> incident_response_testing
%%     incident_response_testing --> optional_proofs
%%     fallback_plans --> incident_response_plans
%%     threat_model --> incident_response_plans
%%
%%     test_monitoring --> optional_proofs
%%     mvp_testing --> test_monitoring
%%

