flowchart TD
    classDef protocol fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef question fill:#9ca3af,stroke:#6b7280,color:#fff
    classDef bad fill:#ef4444,stroke:#b91c1c,color:#fff
    classDef good fill:#22c55e,stroke:#16a34a,color:#fff

    proofs_produced["k Proofs produced"]:::protocol
    proofs_well_distributed["All proofs well distributed"]:::protocol
    proofs_valid["Proofs accurate"]:::protocol
    verifier_correct["Verifiers correct"]:::protocol
    signature_valid["Attester signature accurate"]:::protocol

    stan_global_outage["Global StAN outage"]:::question
    stan_big["> 1/3 of the stake?"]:::question
    stan_huge["> 2/3 of the stake?"]:::question
    stan_partial_outage["Partial StAN outage"]:::question
    all_k_1["Affects every k-subset?"]:::question
    sufficiently_corrleated["Sufficiently correlated?"]:::question
    signature_failure["Signature verification failure"]:::question
    soundness_bug["Soundness bug"]:::question
    completeness_bug["Completeness bug"]:::question
    zkevm_bug["zkEVM bug"]:::question


    attesters_offline["Attesters offline"]:::bad
    not_finalizing["Non-finality"]:::bad
    consensus_failure["Consensus failure"]:::bad
    invalid_transition["Invalid transition accepted"]:::bad

    valid_transition["Valid state transition"]:::good

    proofs_produced -- "no" --> stan_global_outage
    stan_global_outage --> stan_big
    stan_big --"no"--> attesters_offline
    stan_big --"yes"--> stan_huge
    stan_huge --"no"--> not_finalizing
    stan_huge --"yes"--> consensus_failure
    proofs_produced -- "yes" --> proofs_well_distributed

    proofs_well_distributed -- "no" --> stan_partial_outage
    stan_partial_outage --> stan_big
    proofs_well_distributed -- "yes" --> proofs_valid

    proofs_valid -- "yes" --> verifier_correct
    proofs_valid -- "no" --> zkevm_bug
    zkevm_bug --> completeness_bug
    completeness_bug --> all_k_1
    all_k_1 -- "yes" --> stan_big
    zkevm_bug --> soundness_bug
    soundness_bug --> sufficiently_corrleated
    sufficiently_corrleated --> invalid_transition

    verifier_correct -- "no" --> zkevm_bug
    verifier_correct -- "yes" --> signature_valid

    signature_valid -- "no" --> signature_failure
    signature_valid -- "yes" --> valid_transition


